### ISSUE TITLE
Bean theory seems to be broken

### ISSUE THREAD

**Issue by rbommel** [edgarcosta/beantheory#5]
It shows me an old website. Maybe some server is not doing its cronjob?

**Comment by edgarcosta** [comment]
:(

Beantheory went for Thanksgiving break and didn't come back. I might be
able to fix it in a day or so

**Comment by edgarcosta** [comment]
The rogue non utf8 quote in Kudla's (https://www2.bc.edu/benjamin-howard/BC-MIT.html) messed up the deconding.
Now is up and running again.
